# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        types: [python]
    -   id: end-of-file-fixer
        types: [python]
    -   id: check-yaml

-   repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        types: [python]
        files: \.py$
        args: [
            "--remove-all-unused-imports",
            "--expand-star-imports",
            "--ignore-init-module-imports",
            "--in-place"
        ]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        types: [python]
        files: \.py$

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        types: [python]
        files: \.py$
        language_version: python3
